### PR TITLE
Provides a way to check a guess without having to see the answer

### LINKED ISSUE #7: Provide a way to check answer
Currently the only way to check your answer is to see the correct answer.  Should provide a way to compare an answer against your guess and see whether it's right so you can keep working if it's wrong.

### PR DESCRIPTION
**Pull request by jm-welch**
(Fixes #7)

### CODE REVIEW

**Comment by sukima** [comment]
Perfect! :+1: :shipit: !

**Comment by veltman** [comment]
I like this idea a lot, but IIRC `md5sum` would be Linux only, a Mac user would need to use `md5`, so we would need something that works across both.  I also don't think `md5` offers a way to check against a file.  How about:

    echo "John Doe" | $(command -v md5 || command -v md5sum) | grep -q "32cacbec4b918e2fd130fd68cf818ae5" && echo SUCCESS\! || echo WRONG ANSWER, TRY AGAIN.

**Comment by veltman** [comment]
In order to make this case-insensitive without introducing extra stuff into the command, I'll add the hashes of all reasonable lower/uppercase correct answers to the `solution` file and then use this as the check command:

    echo "John Doe" | $(command -v md5 || command -v md5sum) | grep -qf /dev/stdin solution && echo SUCCESS\! || echo WRONG ANSWER, TRY AGAIN.

**Comment by veltman** [comment]
Addressed with 5a9a782

**Pull request closed without merging**
